### ISSUE TITLE
Gnome 46 Support Update We Want

### ISSUE THREAD

**Issue by Vickydmt** [jkitching/soft-brightness-plus#17] opened 2024-03-28 02:26 UTC
Gnome Has Now Having New Version Bro So Please We Are Requesting The Gnome 46 Version Support Bro . Thank You For Your Software Brightness Plus❤️❤️❤️.

**Comment by jkitching** [comment] 2024-03-31 03:59
Merging into existing issue: duplicate of #16.

Thanks For Your Support!

**Comment by jkitching** [comment] 2024-03-31 04:00
Duplicate of #16

**Closed by jkitching** 2024-03-31 03:59 UTC
